[package]
name = "birthbot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
dotenv = "0.15.0"
mongodb = { version = "2.3.1", features = ["bson-chrono-0_4"] }
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[features]
default = []
guild = []