[package]
name = "birthbot"
version = "0.1.0"
edition = "2021"

[dependencies]
datetime = "0.5.2"
dotenv = "0.15.0"
serenity = { version = "0.11", default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[features]
default = []
guild = []