[package]
name = "birthbot"
version = "0.3.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.3.0", features = ["derive"] }
log = "0.4.17"
mongodm = "0.9.1"
poise = "0.5.5"
serde = { version = "1.0.163", features = ["derive"] }
simplelog = "0.12.1"
snafu = "0.7.4"
tokio = "1.28.1"
