[package]
name = "birthbot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
mongodb = "2.3.1"
serenity = { version = "0.11", default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[features]
default = []
guild = []