[package]
name = "birthbot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
dotenvy = "0.15.7"
envy = "0.4.2"
mongodm = "0.9.1"
poise = "0.5.5"
serde = { version = "1.0.163", features = ["derive"] }
snafu = "0.7.4"
tokio = "1.28.1"
